steps:
  - id: gokart
    name: golang:1.16
    entrypoint: 'bash'
    args:
     - -c
     - |
       go install github.com/praetorian-inc/gokart@latest
       gokart scan ./
    waitFor: ['-']

  - name: securego/gosec
    args:  ['./...']
    waitFor: ['-']

  - id: gofmt
    name: gcr.io/cloud-builders/go
    args: ["gofmt", "-s", "-l", "."]
