steps:
# todo
#- id: gokart

  - name: securego/gosec
    args:  ['./...']
    waitFor: ['-']

  - id: gofmt
    name: golang
    entrypoint: 'bash'
    args:
     - -c 
     - |
       test -z $(gofmt -s -l .)
    waitFor: ['-']
